version: "3.7"

services:
# rabbitmq:3.8-management 有附web管理介面;  rabbitmq:3.8 僅有mq
  rmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './rabbitmq_data:/data'
    networks:
      - psystem

networks:
  psystem:
    driver: bridge
